baseURL: https://erik-skopp.de/
title: Erik Skopp
timeout: "120s"
copyright: 'Copyright © 2023-{year} Erik Skopp. All Rights Reserved.'
defaultContentLanguage: de
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# DefaultContentLanguageInSubdir: true
disableLanguages:
   - zh-cn
   - zh-tw
pagination:
  pagerSize: 10
  paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: Kategorien
  series: Serien 
  tag: Tags
  authors: Autoren

build:
  writeStats: true

permalinks:
  news: /:title/
  blog: /:title/

module:
  imports:
    - path: github.com/razonyang/hugo-theme-bootstrap
#   proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  goldmark:
    renderer:
      unsafe: true 
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: true
