languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Erik Skopp"

[params]
  displayName = "Deutsch"
  isoCode = "de"
  rtl = false
  dateFormat = "2. Januar 2006"
  description = "Ein leistungsstarkes, leichtgewichtiges Theme für Hugo."