languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "Erik Skopp"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

  [params.author]
  name = "Erik Skopp"
  image = "img/eskopp.jpg"
  headline = "Mein Blog."
  bio = "def  "
  links = [
        { github = "https://github.com/eskopp/website" }
  ]