# -- Hauptmenü --
# Das Hauptmenü wird im oberen Bereich der Seite angezeigt.
# Zulässige Parameter sind: name, pageRef, page, url, title, weight.
#
# Die einfachste Menükonfiguration ist:
#   name = Der anzuzeigende Name des Menüeintrags
#   pageRef = Die ID der Seite oder Sektion, auf die verlinkt wird
#
# Standardmäßig wird das Menü alphabetisch sortiert.
# Dies kann durch Angabe eines Gewichts überschrieben werden.
# Das Menü wird dann nach Gewicht (aufsteigend) sortiert.

[[main]]
name = "Beiträge"
pageRef = "docs"
weight = 10

#[[main]]
#name = "Showcase"
#parent = "Beispiele"
#pageRef = "examples"
#weight = 30

#[[main]]
#name = "Anleitungen"
#parent = "Beispiele"
#pageRef = "guides"
#weight = 40

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/eskopp/"
weight = 400

[[main]]
identifier = "gitlab"
pre = "gitlab"
url = "https://gitlab.erik-skopp.de/"
weight = 400

# -- Fußzeilenmenü --
# Das Fußzeilenmenü wird ganz unten auf der Seite angezeigt,
# direkt über dem Copyright.
# Konfiguration wie beim Hauptmenü oben.

[[footer]]
name = "Schlagwörter"
pageRef = "tags"
weight = 10

[[footer]]
name = "Autoren"
pageRef = "authors"
weight = 20
