name: Deploy Hugo Site

on:
  push:
    branches: [ main ]

env:
  SSHSERVER: ${{ secrets.SSHSERVER }}
  SSHPW: ${{ secrets.SSHPW }}

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Hugo Build
        run: |
          rm -rf ~/.cache/hugo
          rm -rf go.mod go.sum
          hugo mod init erik-skopp.de
          hugo mod tidy
          hugo mod graph
          hugo --gc --minify --enableGitInfo

      - name: Deploy with lftp (SFTP)
        run: |
          lftp -u webuser,"$SSHPW" sftp://$SSHSERVER <<EOF
            set sftp:auto-confirm yes
            mirror -R --delete --verbose ./public /var/www/erik-skopp.de
            quit
          EOF
