name: Deploy Hugo Site

on:
  push:
    branches: [ main ]

env:
  SSHSERVER: ${{ secrets.SSHSERVER }}
  SSHPW: ${{ secrets.SSHPW }}

jobs:
  deploy:
    name: Build & Deploy via SFTP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Hugo Build
        run: |
          rm -rf ~/.cache/hugo
          rm -rf go.mod go.sum
          hugo mod init erik-skopp.de
          hugo mod tidy
          hugo mod graph
          hugo --gc --minify --enableGitInfo

      - name: Upload via SFTP mirror (webuser)
        env:
          SSHPW: ${{ secrets.SSHPW }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
        run: |
          lftp -u webuser,"$SSHPW" sftp://"$SSHSERVER" -e "\
            set sftp:auto-confirm yes; \
            set sftp:connect-program 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=15 -o ServerAliveCountMax=3'; \
            set net:max-retries 3; \
            set net:reconnect-interval-base 5; \
            set net:timeout 45; \
            cd /erik-skopp.de; \
            mirror --reverse --delete --verbose --only-newer --parallel=4 public .; \
            bye"
 