name: Deploy Hugo Site

on:
  push:
    branches: [ main ]

env:
  SSHSERVER: ${{ secrets.SSHSERVER }}
  SSHPW: ${{ secrets.SSHPW }}

concurrency:
  group: erik-skopp-deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Go (for Hugo Modules)
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Set up Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Hugo Build
        run: |
          # Module-Setup ohne jedes Mal neu zu initialisieren
          hugo mod get
          hugo mod tidy
          hugo --gc --minify --enableGitInfo

      - name: Upload via SFTP mirror (webuser)
        env:
          SSHPW: ${{ secrets.SSHPW }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
        run: |
          lftp -u webuser,"$SSHPW" "sftp://$SSHSERVER" -e '
            set sftp:auto-confirm yes;
            set net:max-retries 3;
            set net:reconnect-interval-base 5;
            set net:timeout 45;
            mkdir -p /var/www/erik-skopp.de;
            mirror --reverse --delete --verbose --only-newer --parallel=4 public /var/www/erik-skopp.de;
            bye
          '
