name: Build & Deploy erik-skopp.de

on:
  push:
    branches: [main]

env:
  SSHSERVER: ${{ secrets.SSHSERVER }}
  SSHPW: ${{ secrets.SSHPW }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: lfs: true
      - uses: actions/setup-go@v6
        with: go-version: 'stable'
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.1'
          extended: true
      - name: Build
        run: |
          hugo mod get
          hugo mod tidy
          hugo --gc --minify --enableGitInfo
      - uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: public
          path: public
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
      - name: Upload via SFTP (webuser)
        env:
          SSHPW: ${{ secrets.SSHPW }}
          SSHSERVER: ${{ secrets.SSHSERVER }}
        run: |
          lftp -u webuser,"$SSHPW" "sftp://$SSHSERVER" -e '
            set sftp:auto-confirm yes;
            set net:max-retries 2;
            set net:timeout 30;
            mkdir -p /var/www/erik-skopp.de;
            mirror --reverse --delete --verbose --only-newer --parallel=4 public /var/www/erik-skopp.de;
            bye
          '
