name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab.erik-skopp.de/erikskopp/website.git"

      - name: Push to GitLab
        run: |
          git push --force gitlab main
