name: GitHub Pages

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Change path
        run: |
          ls -aril
          pwd
          sed -i 's/erik-skopp.de/backup.erik-skopp.de/g' /config/_default/config.yaml

      - name: Install dependencies and build the site
        run: |
          npm update
          hugo mod npm pack
          npm install
          npm audit fix
          npm fund
          hugo mod get
          hugo mod tidy
          hugo --minify --gc --enableGitInfo  # Builds the site and generates the 'public' folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
